import type { NextPage, GetStaticProps, InferGetStaticPropsType } from 'next';
import Head from 'next/head';
import { tw } from 'twind';
import pMap from 'p-map';
import { Client } from '@notionhq/client';
import { PageObjectResponse } from '@notionhq/client/build/src/api-endpoints';
import { useEffect } from 'react';
import { Post } from '../domains/post';
import { getNotionPropertyValue } from '../utils/get-notion-property-value';

// * --------------------------------------------------------------------------- page

const Home: NextPage = ({ posts }: InferGetStaticPropsType<typeof getStaticProps>) => {
  useEffect(() => {
    console.log(posts, 11111111);
  }, [posts]);

  return (
    <div>
      <Head>
        <title>gengarneko.tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={tw`h-screen bg-gainsboro flex flex-col items-center justify-center`}>
        <div className={tw`mt-20`}>
          {posts.map((post: Post, index) => (
            <div key={index}>post title: {post.title}</div>
          ))}
        </div>
      </main>

      <footer>footer</footer>
    </div>
  );
};

// * ---------------------------------------------------------------------------

export const getStaticProps: GetStaticProps = async () => {
  const client = new Client({ auth: process.env.NOTION_ACCESS_TOKEN });
  const id = process.env.NOTION_BLOG_DATABASE_ID;
  const response = await client.databases.query({ database_id: id });

  // * --------------------------- fetchers

  const retrieveSinglePage = (pageId: string) => client.pages.retrieve({ page_id: pageId });

  const retrieveSinglePagePropertyItem = (pageId: string, propertyId: string) =>
    client.pages.properties
      .retrieve({ page_id: pageId, property_id: propertyId })
      .then((res) => ({ ...res, key: propertyId }));

  // * ---------------------------

  const pageIds = response.results.map((page) => page.id);
  const blogPosts = await pMap(pageIds, retrieveSinglePage);

  const getSinglePost = async (page: PageObjectResponse): Promise<Post> => {
    const cover = page.cover && page.cover.type === 'external' ? page.cover.external.url : null;

    const pageId = page.id;
    const propertyIds = Object.values(page.properties).map((item) => item.id);
    const propertyEntries = Object.entries(page.properties);
    const propertyValues = await pMap(propertyIds, (id) => retrieveSinglePagePropertyItem(pageId, id));

    const properties = propertyIds.map((propertyId) => ({
      id: propertyId,
      name: propertyEntries.find(([, { id }]) => id === propertyId)[0],
      value: getNotionPropertyValue(propertyValues.find((item) => item.key === propertyId)),
    }));

    const getPropertyValue = (propertyName: string) =>
      properties.find((property) => property.name === propertyName).value;

    return {
      cover,
      title: getPropertyValue('title'),
      description: getPropertyValue('description'),
      create_time: getPropertyValue('create_time'),
      update_time: getPropertyValue('update_time'),
      likes_count: getPropertyValue('likes_count'),
      views_count: getPropertyValue('views_count'),
      author: getPropertyValue('author'),
      status: getPropertyValue('status'),
      tags: getPropertyValue('tags'),
    };
  };

  const posts: Post[] = await pMap(blogPosts, getSinglePost);

  // * ---------------------------

  return { props: { posts } };
};

export default Home;
