import type { NextPage } from 'next';
import Head from 'next/head';
import { tw } from 'twind';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>gengarneko.tech</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={tw`h-screen bg-gainsboro flex items-center justify-center`}>
        <h1 className={tw`font-bold text(center 5xl white sm:gray-800 md:pink-700)`}>This is Twind!</h1>
      </main>

      <footer>footer</footer>
    </div>
  );
};

export default Home;
